<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LicenseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('licenses')->insert([
            [
                'genre' => '法律・経営',
                'name' => 'ビジネス実務法務検定',
                'grade' => '1級',
                'exam_date' => '2022/12/4',
                'fee' => 12100,
                'status' => '受験する',
            ],
            [
                'genre' => '法律・経営',
                'name' => 'ビジネス実務法務検定',
                'grade' => '2級',
                'exam_date' => null,
                'fee' => 7700,
                'status' => '受験しない',
            ],
            [
                'genre' => '法律・経営',
                'name' => '社労士',
                'grade' => 'その他',
                'exam_date' => null,
                'fee' => 15000,
                'status' => '検討中',
            ],
            [
                'genre' => '法律・経営',
                'name' => '行政書士',
                'grade' => 'その他',
                'exam_date' => null,
                'fee' => 10400,
                'status' => '受験しない',
            ],
            [
                'genre' => '法律・経営',
                'name' => '中小企業診断士',
                'grade' => 'その他',
                'exam_date' => null,
                'fee' => 14500,
                'status' => '受験しない',
            ],
            [
                'genre' => '法律・経営',
                'name' => '予備試験',
                'grade' => 'その他',
                'exam_date' => null,
                'fee' => 17500,
                'status' => '検討中',
            ],
            [
                'genre' => '法律・経営',
                'name' => '司法試験',
                'grade' => 'その他',
                'exam_date' => null,
                'fee' => 28000,
                'status' => '検討中',
            ],
            [
                'genre' => '法律・経営',
                'name' => '知的財産管理技能検定',
                'grade' => '1級',
                'exam_date' => null,
                'fee' => 8900,
                'status' => '検討中',
            ],
            [
                'genre' => '法律・経営',
                'name' => '知的財産管理技能検定',
                'grade' => '2級',
                'exam_date' => null,
                'fee' => 8200,
                'status' => '受験しない',
            ],
            [
                'genre' => '法律・経営',
                'name' => '司法書士',
                'grade' => 'その他',
                'exam_date' => null,
                'fee' => 8000,
                'status' => '検討中',
            ],
            [
                'genre' => '法律・経営',
                'name' => '弁理士',
                'grade' => 'その他',
                'exam_date' => null,
                'fee' => 12000,
                'status' => '検討中',
            ],
            [
                'genre' => '法律・経営',
                'name' => '宅建',
                'grade' => 'その他',
                'exam_date' => null,
                'fee' => 7000,
                'status' => '検討中',
            ],
            [
                'genre' => '法律・経営',
                'name' => '土地家屋調査士',
                'grade' => 'その他',
                'exam_date' => null,
                'fee' => 8300,
                'status' => '検討中',
            ],
            [
                'genre' => '法律・経営',
                'name' => '不動産鑑定士',
                'grade' => 'その他',
                'exam_date' => null,
                'fee' => 13000,
                'status' => '検討中',
            ],
            [
                'genre' => '法律・経営',
                'name' => '敷金診断士',
                'grade' => 'その他',
                'exam_date' => null,
                'fee' => 7800,
                'status' => '検討中',
            ],
            [
                'genre' => '法律・経営',
                'name' => '投資不動産取引士',
                'grade' => 'その他',
                'exam_date' => null,
                'fee' => 24200,
                'status' => '検討中',
            ],
            [
                'genre' => '会計・事務',
                'name' => 'ビジネス数学検定',
                'grade' => '1級',
                'exam_date' => null,
                'fee' => 8800,
                'status' => '検討中',
            ],
            [
                'genre' => '会計・事務',
                'name' => 'ビジネス数学検定',
                'grade' => '2級',
                'exam_date' => null,
                'fee' => 6600,
                'status' => '検討中',
            ],
            [
                'genre' => '会計・事務',
                'name' => 'ビジネス会計検定',
                'grade' => '1級',
                'exam_date' => '2023/1/12',
                'fee' => 11550,
                'status' => '検討中',
            ],
            [
                'genre' => '会計・事務',
                'name' => 'ビジネス会計検定',
                'grade' => '2級',
                'exam_date' => '2023/1/12',
                'fee' => 7480,
                'status' => '受験しない',
            ],
            [
                'genre' => '会計・事務',
                'name' => '日商簿記検定',
                'grade' => '1級',
                'exam_date' => null,
                'fee' => 7850,
                'status' => '受験する',
            ],
            [
                'genre' => '会計・事務',
                'name' => '日商簿記検定',
                'grade' => '2級',
                'exam_date' => null,
                'fee' => 4720,
                'status' => '受験しない',
            ],
            [
                'genre' => '会計・事務',
                'name' => 'FP技能検定',
                'grade' => '1級',
                'exam_date' => null,
                'fee' => 8900,
                'status' => '受験しない',
            ],
            [
                'genre' => '会計・事務',
                'name' => 'FP技能検定',
                'grade' => '2級',
                'exam_date' => null,
                'fee' => 5700,
                'status' => '受験しない',
            ],
            [
                'genre' => '会計・事務',
                'name' => '公認会計士',
                'grade' => 'その他',
                'exam_date' => null,
                'fee' => 19500,
                'status' => '検討中',
            ],
            [
                'genre' => '会計・事務',
                'name' => '税理士',
                'grade' => 'その他',
                'exam_date' => null,
                'fee' => 4000,
                'status' => '検討中',
            ],
            [
                'genre' => '会計・事務',
                'name' => 'BATIC',
                'grade' => 'その他',
                'exam_date' => null,
                'fee' => 5500,
                'status' => '検討中',
            ],
            [
                'genre' => '会計・事務',
                'name' => '貸金業務取扱主任者',
                'grade' => 'その他',
                'exam_date' => null,
                'fee' => 8500,
                'status' => '検討中',
            ],
            [
                'genre' => '会計・事務',
                'name' => '電子会計実務検定',
                'grade' => '1級',
                'exam_date' => null,
                'fee' => 10480,
                'status' => '検討中',
            ],
            [
                'genre' => '会計・事務',
                'name' => '電子会計実務検定',
                'grade' => '2級',
                'exam_date' => null,
                'fee' => 7330,
                'status' => '受験しない',
            ],
            [
                'genre' => 'IT・クリエイティブ',
                'name' => '応用情報技術者',
                'grade' => 'その他',
                'exam_date' => null,
                'fee' => 7500,
                'status' => '受験しない',
            ],
            [
                'genre' => 'IT・クリエイティブ',
                'name' => 'ITストラテジスト',
                'grade' => 'その他',
                'exam_date' => null,
                'fee' => 7500,
                'status' => '受験する',
            ],
            [
                'genre' => 'IT・クリエイティブ',
                'name' => 'プロジェクトマネージャ',
                'grade' => 'その他',
                'exam_date' => null,
                'fee' => 7500,
                'status' => '検討中',
            ],
            [
                'genre' => 'IT・クリエイティブ',
                'name' => 'データベーススペシャリスト',
                'grade' => 'その他',
                'exam_date' => null,
                'fee' => 7500,
                'status' => '検討中',
            ],
            [
                'genre' => 'IT・クリエイティブ',
                'name' => 'ネットワークスペシャリスト',
                'grade' => 'その他',
                'exam_date' => null,
                'fee' => 7500,
                'status' => '検討中',
            ],
            [
                'genre' => 'IT・クリエイティブ',
                'name' => '情報セキュリティマネジメント',
                'grade' => 'その他',
                'exam_date' => null,
                'fee' => 7500,
                'status' => '検討中',
            ],
            [
                'genre' => 'IT・クリエイティブ',
                'name' => 'システム監査技術者',
                'grade' => 'その他',
                'exam_date' => null,
                'fee' => 7500,
                'status' => '受験する',
            ],
            [
                'genre' => 'IT・クリエイティブ',
                'name' => 'システムアーキテクト',
                'grade' => 'その他',
                'exam_date' => null,
                'fee' => 7500,
                'status' => '受験する',
            ],
            [
                'genre' => 'IT・クリエイティブ',
                'name' => 'エンベデッドシステム',
                'grade' => 'その他',
                'exam_date' => null,
                'fee' => 7500,
                'status' => '受験する',
            ],
            [
                'genre' => 'IT・クリエイティブ',
                'name' => 'ITコーディネータ',
                'grade' => 'その他',
                'exam_date' => null,
                'fee' => 19800,
                'status' => '検討中',
            ],
            [
                'genre' => 'IT・クリエイティブ',
                'name' => 'DXビジネス検定',
                'grade' => 'その他',
                'exam_date' => null,
                'fee' => 6600,
                'status' => '検討中',
            ],
            [
                'genre' => 'IT・クリエイティブ',
                'name' => 'AI実装検定',
                'grade' => 'その他',
                'exam_date' => null,
                'fee' => 33000,
                'status' => '受験しない',
            ],
            [
                'genre' => 'IT・クリエイティブ',
                'name' => '色彩検定',
                'grade' => '1級',
                'exam_date' => null,
                'fee' => 15000,
                'status' => '検討中',
            ],
            [
                'genre' => 'IT・クリエイティブ',
                'name' => '色彩検定',
                'grade' => '2級',
                'exam_date' => null,
                'fee' => 10000,
                'status' => '受験しない',
            ],
            [
                'genre' => 'IT・クリエイティブ',
                'name' => 'カラーコーディネーター検定',
                'grade' => 'アドバンス',
                'exam_date' => null,
                'fee' => 7700,
                'status' => '検討中',
            ],
            [
                'genre' => 'IT・クリエイティブ',
                'name' => 'インテリアコーディネーター',
                'grade' => 'その他',
                'exam_date' => null,
                'fee' => 14850,
                'status' => '検討中',
            ],
            [
                'genre' => 'IT・クリエイティブ',
                'name' => 'プロダクトデザイン検定',
                'grade' => '1級',
                'exam_date' => null,
                'fee' => 11000,
                'status' => '検討中',
            ],
            [
                'genre' => 'IT・クリエイティブ',
                'name' => 'プロダクトデザイン検定',
                'grade' => '2級',
                'exam_date' => null,
                'fee' => 11000,
                'status' => '受験しない',
            ],
            [
                'genre' => '語学',
                'name' => '英検',
                'grade' => '1級',
                'exam_date' => null,
                'fee' => 11800,
                'status' => '受験しない',
            ],
            [
                'genre' => '語学',
                'name' => '英検',
                'grade' => '2級',
                'exam_date' => null,
                'fee' => 9000,
                'status' => '受験しない',
            ],
            [
                'genre' => '語学',
                'name' => 'TOEIC',
                'grade' => 'その他',
                'exam_date' => null,
                'fee' => 7810,
                'status' => '受験する',
            ],
            [
                'genre' => '語学',
                'name' => '中国語検定',
                'grade' => '1級',
                'exam_date' => null,
                'fee' => 11800,
                'status' => '検討中',
            ],
            [
                'genre' => '語学',
                'name' => '中国語検定',
                'grade' => '2級',
                'exam_date' => null,
                'fee' => 7800,
                'status' => '受験しない',
            ],
            [
                'genre' => '語学',
                'name' => '国連英検',
                'grade' => 'その他',
                'exam_date' => null,
                'fee' => 12500,
                'status' => '受験しない',
            ],
            [
                'genre' => '車両・船舶',
                'name' => '小型船舶操縦士',
                'grade' => '1級',
                'exam_date' => null,
                'fee' => 28950,
                'status' => '検討中',
            ],
            [
                'genre' => '車両・船舶',
                'name' => '小型船舶操縦士',
                'grade' => '2級',
                'exam_date' => null,
                'fee' => 25900,
                'status' => '受験する',
            ],
            [
                'genre' => 'その他',
                'name' => '数検',
                'grade' => '1級',
                'exam_date' => null,
                'fee' => 8500,
                'status' => '受験する',
            ],
            [
                'genre' => 'その他',
                'name' => '数検',
                'grade' => '2級',
                'exam_date' => null,
                'fee' => 6500,
                'status' => '受験しない',
            ],
            [
                'genre' => 'その他',
                'name' => '統計検定',
                'grade' => '1級',
                'exam_date' => null,
                'fee' => 10000,
                'status' => '検討中',
            ],
            [
                'genre' => 'その他',
                'name' => '統計検定',
                'grade' => '2級',
                'exam_date' => null,
                'fee' => 5000,
                'status' => '検討中',
            ],
            [
                'genre' => 'その他',
                'name' => '電気通信主任技術者',
                'grade' => 'その他',
                'exam_date' => null,
                'fee' => 18700,
                'status' => '検討中',
            ],
            [
                'genre' => 'その他',
                'name' => '福祉ロボット検定',
                'grade' => 'その他',
                'exam_date' => null,
                'fee' => 16870,
                'status' => '検討中',
            ],
            [
                'genre' => 'その他',
                'name' => 'ドローン検定',
                'grade' => '1級',
                'exam_date' => null,
                'fee' => 18800,
                'status' => '検討中',
            ],
            [
                'genre' => 'その他',
                'name' => 'ドローン検定',
                'grade' => '2級',
                'exam_date' => null,
                'fee' => 12900,
                'status' => '検討中',
            ],
        ]);
    }
}
